apiVersion: skaffold/v1beta12
kind: Config
build:
  artifacts:
  - image: springtrader
    docker:
      target: runner
      cacheFrom:
        - docker.artifactory.liatr.io/liatrio/springtrader-builder:latest
        - docker.artifactory.liatr.io/liatrio/springtrader-runner:latest
  - image: sqlfdb 
    docker:
      target: sqlfdb
      cacheFrom:
        - docker.artifactory.liatr.io/liatrio/springtrader-builder:latest
        - docker.artifactory.liatr.io/liatrio/springtrader-runner:latest
  local: {}

deploy:
  helm:
    flags:
      upgrade: ["--timeout", "600"]
      install: ["--timeout", "600"]
    releases:
      - name: springtrader 
        chartPath: ./charts/springtrader
        wait: true
        values:
          image: springtrader 
          sqlfdb: sqlfdb 
        setValueTemplates:
          istioDomain: "{{.ISTIO_DOMAIN}}"
profiles:
- name: microk8s
  activation:
  - kubeContext: microk8s
  patches:
  - op: add
    path: /deploy/helm/releases/0/setValues
    value: 
      storageClassName: microk8s-hostpath
