{{- if not (eq .Values.istioDomain "<no value>") -}}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: "{{ .Chart.Name }}-gateway"
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - {{ .Chart.Name }}.{{ .Values.istioDomain }}
    port:
      name: http
      number: 80
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - {{ .Chart.Name }}.{{ .Values.istioDomain }}
    port:
      name: https-default
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      serverCertificate: "sds"
      privateKey: "sds"
      credentialName: "{{ .Release.Namespace }}-certificate"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "{{ .Chart.Name }}"
spec:
  hosts:
  - {{ .Chart.Name }}.{{ .Values.istioDomain }}
  gateways:
  - "{{ .Chart.Name }}-gateway"
  http:
  - route:
    - destination:
        host: springtrader
        port:
          number: 8080
{{- end }}
